---
# Source: pixie-chart/templates/01_nats.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:

  labels:

    app: pl-monitoring
  name: pl:nats-operator
  namespace: default
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - nats.io
  resources:
  - natsclusters
  - natsserviceroles
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - pods
  - pods/exec
  - pods/log
  - services
  - serviceaccounts
  - serviceaccounts/token
  - endpoints
  - events
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
---
# Source: pixie-chart/templates/01_nats.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:

  labels:

    app: pl-monitoring
  name: pl:nats-server
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - '*'
---
# Source: pixie-chart/templates/04_vizier_persistent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
    vizier-updater-dep: "true"
  name: pl-updater-role
  namespace: default
rules:
- apiGroups:
  - ""
  - apps
  - rbac.authorization.k8s.io
  - extensions
  - etcd.database.coreos.com
  - batch
  - nats.io
  - policy
  resources:
  - clusterroles
  - clusterrolebindings
  - configmaps
  - secrets
  - pods
  - services
  - deployments
  - daemonsets
  - persistentvolumes
  - persistentvolumeclaims
  - roles
  - rolebindings
  - serviceaccounts
  - etcdclusters.etcd.database.coreos.com
  - etcdclusters
  - statefulsets
  - cronjobs
  - jobs
  - natsclusters
  - podsecuritypolicies
  verbs:
  - '*'
---
# Source: pixie-chart/templates/04_vizier_persistent.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-cloud-connector-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services
  - endpoints
  - namespaces
  - jobs
  - events
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
---
# Source: pixie-chart/templates/04_vizier_persistent.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
  name: pl-node-view
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list
---
# Source: pixie-chart/templates/04_vizier_persistent.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
  name: pl-vizier-certmgr
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - '*'
---
# Source: pixie-chart/templates/04_vizier_persistent.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
  name: pl-vizier-metadata
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - namespaces
  verbs:
  - '*'
---
