---
# Source: pixie-chart/templates/04_vizier_persistent.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
  name: vizier-pem
  namespace: default
spec:
  selector:
    matchLabels:
      app: pl-monitoring
      component: vizier
      name: vizier-pem
  template:
    metadata:
      annotations:

      labels:

        app: pl-monitoring
        component: vizier
        name: vizier-pem
        plane: data
    spec:
      containers:
      - args: []
        env:
        - name: TCMALLOC_SAMPLE_PARAMETER
          value: "1048576"
        - name: PL_CLIENT_TLS_CERT
          value: /certs/client.crt
        - name: PL_CLIENT_TLS_KEY
          value: /certs/client.key
        - name: PL_TLS_CA_CERT
          value: /certs/ca.crt
        - name: PL_DISABLE_SSL
          value: "false"
        - name: PL_HOST_PATH
          value: /host
        - name: PL_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PL_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-signing-key
              name: pl-cluster-secrets
        image: gcr.io/pixie-prod/vizier/pem_image:0.7.8
        name: pem
        resources:
          limits:
            memory: "2Gi"
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
            - SYS_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: host-root
          readOnly: true
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /certs
          name: certs
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      initContainers:
      - command:
        - sh
        - -c
        - 'set -x; URL="https://${SERVICE_NAME}:${SERVICE_PORT}/healthz"; until [
          $(curl -m 0.5 -s -o /dev/null -w "%{http_code}" -k ${URL}) -eq 200 ]; do
          echo "waiting for ${URL}" sleep 2; done; '
        env:
        - name: SERVICE_NAME
          value: vizier-query-broker
        - name: SERVICE_PORT
          value: "50300"
        image: gcr.io/pixie-prod/pixie-prod-artifacts/curl:1.0
        name: qb-wait
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: host-root
      - hostPath:
          path: /sys
          type: Directory
        name: sys
      - name: certs
        secret:
          secretName: service-tls-certs
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 20
    type: RollingUpdate
---
