---
# Source: pixie-chart/templates/01_nats.yaml
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  annotations:

  labels:

    app: pl-monitoring
  name: pl-nats
  namespace: default
spec:
  size: 1
  tls:
    serverSecret: service-tls-certs
    serverSecretCAFileName: ca.crt
    serverSecretCertFileName: server.crt
    serverSecretKeyFileName: server.key
  version: 1.3.0
