# Source: pixie-chart/templates/04_vizier_persistent.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
  name: metadata-pv-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
