---
# Source: pixie-chart/templates/04_vizier_persistent.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: pl-psp-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-psp
subjects:
- kind: ServiceAccount
  name: updater-service-account
  namespace: default
---
