---
# Source: pixie-chart/templates/00_secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:

  creationTimestamp: null
  labels:

  name: pl-cluster-secrets
  namespace: default
stringData:
  sentry-dsn: https://a8a635734bb840799befb63190e904e0@o324879.ingest.sentry.io/5203506
---
# Source: pixie-chart/templates/00_secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:

  creationTimestamp: null
  labels:

  name: pl-deploy-secrets
  namespace: default
stringData:
  deploy-key: "80201b40-91bc-4893-ab59-521a16c0a97a"
---
# Source: pixie-chart/templates/00_secrets.yaml
apiVersion: v1
data:
  PL_CLOUD_ADDR: "withpixie.ai:443"
  PL_CLUSTER_NAME: "kubernetescluster1"
  PL_UPDATE_CLOUD_ADDR: "withpixie.ai:443"
kind: ConfigMap
metadata:
  annotations:

  creationTimestamp: null
  labels:

  name: pl-cloud-config
  namespace: default
---
# Source: pixie-chart/templates/00_secrets.yaml
apiVersion: v1
data:
  PL_CUSTOM_ANNOTATIONS: ""
  PL_CUSTOM_LABELS: ""
  PL_ETCD_OPERATOR_ENABLED: "false"
  PL_MD_ETCD_SERVER: "https://etcd.default.svc:2379"
  PX_MEMORY_LIMIT: ""
kind: ConfigMap
metadata:
  annotations:

  creationTimestamp: null
  labels:

  name: pl-cluster-config
  namespace: default
---
# Source: pixie-chart/templates/00_secrets.yaml
apiVersion: v1
data:
  PL_BOOTSTRAP_MODE: "false"
  PL_BOOTSTRAP_VERSION: ""
kind: ConfigMap
metadata:
  annotations:

  creationTimestamp: null
  labels:

    component: vizier
  name: pl-cloud-connector-bootstrap-config
  namespace: default
---
