---
# Source: pixie-chart/templates/01_nats.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:

  labels:

    app: pl-monitoring
  name: nats-operator
  namespace: default
---
# Source: pixie-chart/templates/01_nats.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:

  labels:

    app: pl-monitoring
  name: nats-server
  namespace: default
---
# Source: pixie-chart/templates/04_vizier_persistent.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
  name: cloud-conn-service-account
  namespace: default
---
# Source: pixie-chart/templates/04_vizier_persistent.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:

  labels:

    app: pl-monitoring
    component: vizier
    vizier-bootstrap: "true"
    vizier-updater-dep: "true"
  name: updater-service-account
  namespace: default
---
